name: hover_effect
description: Hover - Tilt 3D Effect Takes any child witget and enables Hover/Tilt 3D functionality to your widgets.
version: 0.5.0
author: Mariano Zorrilla <mkiisoft@gmail.com>
homepage: https://github.com/mkiisoft/hover_effect

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
